package com.midnight.kuira.contract

import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.BYTE_ARRAY
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT

/**
 * Build-time codegen of a typed Kotlin facade per Compact contract, derived
 * from the compiler's `contract-info.json` ABI.
 *
 * The generated class is a THIN delegate over [MidnightContract.call] — it does
 * not reimplement the runtime pipeline (state fetch -> execute -> prove ->
 * balance -> submit). It only gives a typed surface so a wrong-typed circuit
 * argument is a compile error instead of a runtime `ArgConverter` surprise.
 *
 * For the tifosi `voting` contract this emits:
 *
 * ```kotlin
 * class VotingContract(private val handle: MidnightContract) {
 *     suspend fun createPoll(question: String, options: String, onProgress: ...) =
 *         handle.call("createPoll", question, options, onProgress = onProgress)
 *     suspend fun castVote(optionIdx: java.math.BigInteger, onProgress: ...) =
 *         handle.call("castVote", optionIdx, onProgress = onProgress)
 *     suspend fun closePoll(onProgress: ...) =
 *         handle.call("closePoll", onProgress = onProgress)
 * }
 * ```
 *
 * Structs and enums referenced by circuit arguments are emitted as generated
 * `data class` / `enum class` declarations in the same file, so the typed
 * surface is self-contained. Constructors are NOT in the ABI, so no typed
 * `deploy` is generated — deploy stays on the raw [MidnightContract.deploy].
 *
 * Pure (no Gradle types) so it is unit-testable directly: feed an ABI string,
 * assert on the produced source.
 */
internal object ContractApiGenerator {

    /** Package the generated facade + supporting types live in. */
    const val GENERATED_PACKAGE = "com.midnight.kuira.contract.generated"

    private val MIDNIGHT_CONTRACT = ClassName("com.midnight.kuira.core.compact", "MidnightContract")
    private val TRANSACTION_RECEIPT = ClassName("com.midnight.kuira.core.compact", "TransactionReceipt")
    private val CONTRACT_CALL_STAGE = ClassName("com.midnight.kuira.core.compact", "ContractCallStage")
    private val BIG_INTEGER = ClassName("java.math", "BigInteger")
    private val LIST = ClassName("kotlin.collections", "List")

    /**
     * The `onProgress` parameter type, matching [MidnightContract.call]:
     * `(suspend (ContractCallStage) -> Unit)?`.
     */
    private val ON_PROGRESS_TYPE: TypeName =
        LambdaTypeName.get(
            parameters = listOf(ParameterSpec.unnamed(CONTRACT_CALL_STAGE)),
            returnType = UNIT,
        )
            .copy(suspending = true)
            .copy(nullable = true)

    /**
     * Generate the [FileSpec] for one contract.
     *
     * @param alias the managed-dir name (e.g. `voting`) — drives the class name.
     * @param contractInfoJson the raw `contract-info.json` text.
     */
    fun generate(alias: String, contractInfoJson: String): FileSpec {
        val root = JsonValue.parse(contractInfoJson) as? JsonObject
            ?: error("contract-info.json is not a JSON object")
        val circuits = (root["circuits"] as? JsonArray)?.items.orEmpty()

        // Collect generated supporting types (Structs -> data class, Enums ->
        // enum class), de-duplicated by name across all circuit arguments.
        val supporting = SupportingTypes()

        val className = facadeClassName(alias)
        val facade = TypeSpec.classBuilder(className)
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("handle", MIDNIGHT_CONTRACT)
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("handle", MIDNIGHT_CONTRACT, KModifier.PRIVATE)
                    .initializer("handle")
                    .build(),
            )

        for (circuit in circuits) {
            val obj = circuit as? JsonObject ?: continue
            facade.addFunction(buildCircuitFun(obj, supporting))
        }

        val fileBuilder = FileSpec.builder(GENERATED_PACKAGE, className)
            .addFileComment(
                "Generated by the Kuira contract plugin from contract-info.json — do not edit.\n" +
                    "Typed facade over MidnightContract.call(...) for the \"%L\" contract.",
                alias,
            )
            .addType(facade.build())

        // Emit supporting types after the facade, in a stable (insertion) order.
        for (type in supporting.all()) {
            fileBuilder.addType(type)
        }

        return fileBuilder.build()
    }

    /** `voting` -> `VotingContract`, `penalty` -> `PenaltyContract`. */
    private fun facadeClassName(alias: String): String =
        alias.split('-', '_', '.')
            .filter { it.isNotEmpty() }
            .joinToString("") { part -> part.replaceFirstChar { it.uppercaseChar() } } + "Contract"

    private fun buildCircuitFun(circuit: JsonObject, supporting: SupportingTypes): FunSpec {
        val name = (circuit["name"] as? JsonString)?.value
            ?: error("circuit missing name")
        val args = (circuit["arguments"] as? JsonArray)?.items.orEmpty()

        val fn = FunSpec.builder(name)
            .addModifiers(KModifier.SUSPEND)
            .returns(TRANSACTION_RECEIPT)

        // Delegated call: handle.call("name", a, b, onProgress = onProgress)
        val callArgs = StringBuilder("\"%L\"")
        val callFormatArgs = mutableListOf<Any>(name)

        for (arg in args) {
            val argObj = arg as? JsonObject ?: continue
            val argName = (argObj["name"] as? JsonString)?.value ?: error("argument missing name")
            val argType = argObj["type"] as? JsonObject ?: error("argument '$argName' missing type")
            val kotlinType = mapType(argType, supporting)
            fn.addParameter(argName, kotlinType)
            callArgs.append(", %N")
            callFormatArgs.add(argName)
        }

        val onProgress = ParameterSpec.builder("onProgress", ON_PROGRESS_TYPE)
            .defaultValue("null")
            .build()
        fn.addParameter(onProgress)
        callArgs.append(", onProgress = %N")
        callFormatArgs.add(onProgress)

        // A circuit result is not modelled as a typed return: call() always yields
        // a TransactionReceipt (an empty Tuple is the circuit's unit return today).
        fn.addStatement("return handle.call($callArgs)", *callFormatArgs.toTypedArray())
        return fn.build()
    }

    /**
     * Map one ABI type node to its Kotlin [TypeName], registering any Struct/Enum
     * it transitively references with [supporting].
     *
     * The closed ABI vocabulary (10 forms):
     *  - `Uint` / `Field`        -> BigInteger
     *  - `Boolean`               -> Boolean
     *  - `Bytes`                 -> ByteArray
     *  - `Vector`                -> List<inner>
     *  - `Tuple` (empty)         -> Unit ; (non-empty) -> generated data class
     *  - `Struct`                -> generated data class
     *  - `Enum`                  -> generated enum class
     *  - `Opaque` tsType=string  -> String ; else -> ByteArray (passthrough)
     *  - `Alias`                 -> transparent (its inner type)
     */
    private fun mapType(type: JsonObject, supporting: SupportingTypes): TypeName {
        val name = (type["type-name"] as? JsonString)?.value
            ?: error("type node missing type-name")
        return when (name) {
            "Uint", "Field" -> BIG_INTEGER
            "Boolean" -> BOOLEAN
            "Bytes" -> BYTE_ARRAY
            "Vector" -> {
                val inner = type["type"] as? JsonObject
                    ?: error("Vector missing inner type")
                LIST.parameterizedBy(mapType(inner, supporting))
            }
            "Tuple" -> {
                val types = (type["types"] as? JsonArray)?.items.orEmpty()
                if (types.isEmpty()) {
                    UNIT
                } else {
                    supporting.registerTuple(types.map { it as JsonObject }) { t -> mapType(t, supporting) }
                }
            }
            "Struct" -> registerStruct(type, supporting)
            "Enum" -> registerEnum(type, supporting)
            "Opaque" -> {
                val ts = (type["tsType"] as? JsonString)?.value
                if (ts == "string") STRING else BYTE_ARRAY
            }
            "Alias" -> {
                val inner = type["type"] as? JsonObject
                    ?: error("Alias missing inner type")
                mapType(inner, supporting)
            }
            else -> error("unsupported ABI type-name: $name")
        }
    }

    private fun registerStruct(type: JsonObject, supporting: SupportingTypes): TypeName {
        val structName = (type["name"] as? JsonString)?.value
            ?: error("Struct missing name")
        val elements = (type["elements"] as? JsonArray)?.items.orEmpty()
        return supporting.registerStruct(structName, elements.map { it as JsonObject }) { elemType ->
            mapType(elemType, supporting)
        }
    }

    private fun registerEnum(type: JsonObject, supporting: SupportingTypes): TypeName {
        val enumName = (type["name"] as? JsonString)?.value
            ?: error("Enum missing name")
        val elements = (type["elements"] as? JsonArray)?.items.orEmpty()
            .map { (it as JsonString).value }
        return supporting.registerEnum(enumName, elements)
    }
}

/**
 * Accumulates generated supporting types (Structs -> data classes, Enums -> enum
 * classes, non-empty Tuples -> positional data classes), de-duplicated by name,
 * in insertion order. Returns a [ClassName] in the generated package for each.
 */
private class SupportingTypes {
    private val types = LinkedHashMap<String, TypeSpec>()
    private val pkg = ContractApiGenerator.GENERATED_PACKAGE

    fun registerStruct(
        name: String,
        elements: List<JsonObject>,
        mapElement: (JsonObject) -> TypeName,
    ): ClassName {
        if (!types.containsKey(name)) {
            // Reserve the slot before recursing so a self/mutually-referential
            // struct doesn't infinitely recurse (compactc nests but is acyclic
            // in practice; this is belt-and-braces).
            types[name] = PLACEHOLDER
            val ctor = FunSpec.constructorBuilder()
            val builder = TypeSpec.classBuilder(name).addModifiers(KModifier.DATA)
            for (element in elements) {
                val elemName = (element["name"] as? JsonString)?.value
                    ?: error("struct '$name' element missing name")
                val elemType = element["type"] as? JsonObject
                    ?: error("struct '$name' element '$elemName' missing type")
                val kt = mapElement(elemType)
                ctor.addParameter(elemName, kt)
                builder.addProperty(
                    PropertySpec.builder(elemName, kt).initializer(elemName).build(),
                )
            }
            types[name] = builder.primaryConstructor(ctor.build()).build()
        }
        return ClassName(pkg, name)
    }

    fun registerEnum(name: String, constants: List<String>): ClassName {
        if (!types.containsKey(name)) {
            val builder = TypeSpec.enumBuilder(name)
            for (c in constants) builder.addEnumConstant(c)
            types[name] = builder.build()
        }
        return ClassName(pkg, name)
    }

    fun registerTuple(
        elementTypes: List<JsonObject>,
        mapElement: (JsonObject) -> TypeName,
    ): ClassName {
        // Deterministic name from arity so identical-arity tuples collapse to one
        // type. compactc rarely emits non-empty tuple ARGS, but the vocabulary
        // allows them, so this stays exhaustive.
        val name = "Tuple${elementTypes.size}"
        if (!types.containsKey(name)) {
            types[name] = PLACEHOLDER
            val ctor = FunSpec.constructorBuilder()
            val builder = TypeSpec.classBuilder(name).addModifiers(KModifier.DATA)
            elementTypes.forEachIndexed { i, t ->
                val field = "field$i"
                val kt = mapElement(t)
                ctor.addParameter(field, kt)
                builder.addProperty(PropertySpec.builder(field, kt).initializer(field).build())
            }
            types[name] = builder.primaryConstructor(ctor.build()).build()
        }
        return ClassName(pkg, name)
    }

    fun all(): List<TypeSpec> = types.values.filter { it !== PLACEHOLDER }

    companion object {
        // Sentinel held while a struct is being built so a cyclic reference is a
        // no-op re-entry rather than infinite recursion.
        private val PLACEHOLDER: TypeSpec = TypeSpec.classBuilder("__placeholder__").build()
    }
}
